# Application settings available as Rails.application.config.settings
#
# All values in this file are namespaced under Rails.application.config.settings
# and will not conflict with other configuration values in Rails.application.config.
# Settings are manually applied to the correct config var as needed in specific initializers.
# e.g. config/initializers/devise.rb

common: &common
  # Downcased and trimmed app name for namespaces.
  # Safest to start with a letter rather than a number.
  # See locales/en.yml for setting your app's user facing brand name.
  app_name: 'biogeochemistry'

  social:
    facebook: 'https://www.facebook.com/is.markelov'
    twitter: 'https://twitter.com/pycckuu2000'

  contact:
    email: 'is.markelov@gmail.com'
    phone: '+33 6 95 32 97 91'

  session:
    key: '_biogeochemistry_session'
    expire_after: <%= 30.days %>

  rack:
    # Timeout request after 20 seconds
    timeout: 20

  mail:
    layout: 'emails/email'
    from: 'is.markelov@gmail.com'


# Default ENV vars.
# Set to development values for convenience and override in production by setting ENV on the server.
# As a best practice, do not put production values in this file for security reasons.
default_env: &default_env
  # From address to use when sending email
  MAIL_HOST: 'localhost:3000'

  # Host used to determine direct requests vs CDN.
  # See RobotsController.
  CANONICAL_HOST: 'biogeochemistry.herokuapp.com'

  AUTH_FACEBOOK_KEY: ENV['AUTH_FACEBOOK_KEY']
  AUTH_FACEBOOK_SECRET: ENV['AUTH_FACEBOOK_SECRET']
  AUTH_TWITTER_KEY: ENV['AUTH_TWITTER_KEY']
  AUTH_TWITTER_SECRET: ENV['AUTH_TWITTER_SECRET']

  # Devise password encryption keys.
  # Channging the keys will invalidate user passwords,
  # forcing users to use the forgot password feature.
  # TODO: make new keys with `rake secret`
  DEVISE_SECRET_KEY: ENV['DEVISE_SECRET_KEY']
  DEVISE_PEPPER: ENV['DEVISE_PEPPER']

  # Signed cookie encryption key.
  # TODO: make new key with `rake secret`
  SECRET_KEY_BASE: ENV['SECRET_KEY_BASE']

  # Redis server used by Sidekiq, cache, etc.
  REDIS_URL: 'redis://localhost:6379/0'

  # Airbrake/Errbit configuration
  AIRBRAKE_API_KEY: ENV['AIRBRAKE_API_KEY']
  AIRBRAKE_HOST: ENV['AIRBRAKE_HOST']


development:
  <<: *common
  env:
    <<: *default_env
    ALLOW_EMAIL_PREVIEW: true

test:
  <<: *common
  env:
    <<: *default_env

staging:
  <<: *common
  env:
    <<: *default_env

production:
  <<: *common
  env:
    # Set dummy key so rake assets:precompile succeeds
    DEVISE_SECRET_KEY: 'asdasd234asd'
